package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTBreak.java */

public class ASTBreak extends SimpleNode {
  public ASTBreak(int id) {
    super(id);
  }

  public ASTBreak(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
