/* Generated By:JJTree: Do not edit this line. ASTgSetFillColor.java */

public class ASTgSetFillColor extends SimpleNode {
  public ASTgSetFillColor(int id) {
    super(id);
  }

  public ASTgSetFillColor(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
