package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetLineWidth.java */

public class ASTgSetLineWidth extends SimpleNode {
  public ASTgSetLineWidth(int id) {
    super(id);
  }

  public ASTgSetLineWidth(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
