package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgClearWindow.java */

public class ASTgClearWindow extends SimpleNode {
  public ASTgClearWindow(int id) {
    super(id);
  }

  public ASTgClearWindow(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
