package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetTextColor.java */

public class ASTgSetTextColor extends SimpleNode {
  public ASTgSetTextColor(int id) {
    super(id);
  }

  public ASTgSetTextColor(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
