package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgDrawImage.java */

public class ASTgDrawImage extends SimpleNode {
  public ASTgDrawImage(int id) {
    super(id);
  }

  public ASTgDrawImage(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
