package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetFont.java */

public class ASTgSetFont extends SimpleNode {
  public ASTgSetFont(int id) {
    super(id);
  }

  public ASTgSetFont(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
