package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetArrowType.java */

public class ASTgSetArrowType extends SimpleNode {
  public ASTgSetArrowType(int id) {
    super(id);
  }

  public ASTgSetArrowType(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
