/* Generated By:JJTree: Do not edit this line. ASTgDrawCircle.java */

public class ASTgDrawCircle extends SimpleNode {
  public ASTgDrawCircle(int id) {
    super(id);
  }

  public ASTgDrawCircle(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
