package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetArrowDir.java */

public class ASTgSetArrowDir extends SimpleNode {
  public ASTgSetArrowDir(int id) {
    super(id);
  }

  public ASTgSetArrowDir(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
