package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgOpenGraphWindow.java */

public class ASTgOpenGraphWindow extends SimpleNode {
  public ASTgOpenGraphWindow(int id) {
    super(id);
  }

  public ASTgOpenGraphWindow(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
