package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetOrigin.java */

public class ASTgSetOrigin extends SimpleNode {
  public ASTgSetOrigin(int id) {
    super(id);
  }

  public ASTgSetOrigin(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
