package pen.Interpreter.ja;
/* Generated By:JJTree: Do not edit this line. ASTgSetLineShape.java */

public class ASTgSetLineShape extends SimpleNode {
  public ASTgSetLineShape(int id) {
    super(id);
  }

  public ASTgSetLineShape(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
