/* Generated By:JJTree: Do not edit this line. ASTAppend.java */

public class ASTAppend extends SimpleNode {
  public ASTAppend(int id) {
    super(id);
  }

  public ASTAppend(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
