/* Generated By:JJTree: Do not edit this line. ASTDfp.java Version 4.3 */

public class ASTDfp extends SimpleNode {
	public ASTDfp(int id) {
		super(id);
	}

	public ASTDfp(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
