/* Generated By:JJTree: Do not edit this line. ASTNull.java */

public class ASTEXTRA_STR extends SimpleNode {
  public ASTEXTRA_STR(int id) {
    super(id);
  }

  public ASTEXTRA_STR(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

	/** customizing codes **/
	public char[] char_code = new char[2];
}
