/* Generated By:JJTree: Do not edit this line. ASTgWindowOpen.java */

public class ASTgOpenWindow extends SimpleNode {
  public ASTgOpenWindow(int id) {
    super(id);
  }

  public ASTgOpenWindow(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
