/* Generated By:JJTree: Do not edit this line. ASTgWindowClose.java */

public class ASTgCloseWindow extends SimpleNode {
  public ASTgCloseWindow(int id) {
    super(id);
  }

  public ASTgCloseWindow(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
