/* Generated By:JJTree: Do not edit this line. ASTgSetFontSize.java */

public class ASTgSetFontSize extends SimpleNode {
  public ASTgSetFontSize(int id) {
    super(id);
  }

  public ASTgSetFontSize(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
