/* Generated By:JJTree: Do not edit this line. ASTgFillCircle.java */

public class ASTgFillCircle extends SimpleNode {
  public ASTgFillCircle(int id) {
    super(id);
  }

  public ASTgFillCircle(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
