/* Generated By:JJTree: Do not edit this line. ASTgDrawPolyline.java */

public class ASTgDrawPolyline extends SimpleNode {
  public ASTgDrawPolyline(int id) {
    super(id);
  }

  public ASTgDrawPolyline(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
