/* Generated By:JJTree: Do not edit this line. ASTgSaveWindow.java */

public class ASTgSaveWindow extends SimpleNode {
  public ASTgSaveWindow(int id) {
    super(id);
  }

  public ASTgSaveWindow(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
