/* Generated By:JJTree: Do not edit this line. ASTInt2Str.java */

public class ASTInt2Str extends SimpleNode {
  public ASTInt2Str(int id) {
    super(id);
  }

  public ASTInt2Str(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
