/* Generated By:JJTree: Do not edit this line. ASTCase.java */

public class ASTCase extends SimpleNode {
  public ASTCase(int id) {
    super(id);
  }

  public ASTCase(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
