/* Generated By:JJTree: Do not edit this line. ASTgSetRepaintFlag.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgSetRepaintFlag extends SimpleNode {
  public ASTgSetRepaintFlag(int id) {
    super(id);
  }

  public ASTgSetRepaintFlag(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=532ec7b9ee94ddced47e3243680f1d60 (do not edit this line) */
