/* Generated By:JJTree: Do not edit this line. ASTgRepaint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgRepaint extends SimpleNode {
  public ASTgRepaint(int id) {
    super(id);
  }

  public ASTgRepaint(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c6e7a717f5316adbfdd9b93bc2adce62 (do not edit this line) */
