/* Generated By:JJTree: Do not edit this line. ASTgRepaint.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgRepaint extends SimpleNode {
  public ASTgRepaint(int id) {
    super(id);
  }

  public ASTgRepaint(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c813d17340775060a3b5c0870a79c9cc (do not edit this line) */
