/* Generated By:JavaCC: Do not edit this line. IntVParserTreeConstants.java Version 5.0 */
public interface IntVParserTreeConstants
{
  public int JJTINTVUNIT = 0;
  public int JJTERROROCCUR = 1;
  public int JJTFUNCTION = 2;
  public int JJTBLOCK = 3;
  public int JJTFUNCTIONVAR = 4;
  public int JJTVARDECL = 5;
  public int JJTDECL = 6;
  public int JJTARRAY = 7;
  public int JJTVOID = 8;
  public int JJTASSIGNSTATS = 9;
  public int JJTASSIGNSTAT = 10;
  public int JJTIFSTAT = 11;
  public int JJTREPEATUNTIL = 12;
  public int JJTFORSTATADD = 13;
  public int JJTWHILESWITCHFOR = 14;
  public int JJTCASE = 15;
  public int JJTLABEL = 16;
  public int JJTGETSTAT = 17;
  public int JJTPUTSTAT = 18;
  public int JJTORNODE = 19;
  public int JJTANDNODE = 20;
  public int JJTNOTNODE = 21;
  public int JJTEQNODE = 22;
  public int JJTNTNODE = 23;
  public int JJTLSNODE = 24;
  public int JJTGTNODE = 25;
  public int JJTLENODE = 26;
  public int JJTGENODE = 27;
  public int JJTADDNODE = 28;
  public int JJTSUBNODE = 29;
  public int JJTMULNODE = 30;
  public int JJTDIVNODE = 31;
  public int JJTSURNODE = 32;
  public int JJTMINNODE = 33;
  public int JJTGET = 34;
  public int JJTRANDOM = 35;
  public int JJTSINE = 36;
  public int JJTCOSINE = 37;
  public int JJTTANGENT = 38;
  public int JJTSQRT = 39;
  public int JJTFLOOR = 40;
  public int JJTCEIL = 41;
  public int JJTROUND = 42;
  public int JJTABS = 43;
  public int JJTLOG = 44;
  public int JJTINT = 45;
  public int JJTLONG = 46;
  public int JJTLENGTH = 47;
  public int JJTAPPEND = 48;
  public int JJTSUBSTRING = 49;
  public int JJTINSERT = 50;
  public int JJTREPLACE = 51;
  public int JJTEXTRACT = 52;
  public int JJTSTR2INT = 53;
  public int JJTINT2STR = 54;
  public int JJTCOMPARE = 55;
  public int JJTGOPENWINDOW = 56;
  public int JJTGOPENGRAPHWINDOW = 57;
  public int JJTGCLOSEWINDOW = 58;
  public int JJTGCLEARWINDOW = 59;
  public int JJTGSAVEWINDOW = 60;
  public int JJTGSETORIGIN = 61;
  public int JJTGSETMAP = 62;
  public int JJTGSETFILLCOLOR = 63;
  public int JJTGSETLINECOLOR = 64;
  public int JJTGSETTEXTCOLOR = 65;
  public int JJTGSETFONT = 66;
  public int JJTGSETFONTTYPE = 67;
  public int JJTGSETFONTSIZE = 68;
  public int JJTGSETDOTSHAPE = 69;
  public int JJTGSETARROWDIR = 70;
  public int JJTGSETARROWTYPE = 71;
  public int JJTGSETLINESHAPE = 72;
  public int JJTGSETLINEWIDTH = 73;
  public int JJTGDRAWPOINT = 74;
  public int JJTGDRAWLINE = 75;
  public int JJTGDRAWTEXT = 76;
  public int JJTGDRAWCIRCLE = 77;
  public int JJTGFILLCIRCLE = 78;
  public int JJTGDRAWOVAL = 79;
  public int JJTGFILLOVAL = 80;
  public int JJTGDRAWBOX = 81;
  public int JJTGFILLBOX = 82;
  public int JJTGDRAWARC = 83;
  public int JJTGFILLARC = 84;
  public int JJTGDRAWPOLYGON = 85;
  public int JJTGFILLPOLYGON = 86;
  public int JJTGDRAWPOLYLINE = 87;
  public int JJTGDRAWIMAGE = 88;
  public int JJTFILE_OPENR = 89;
  public int JJTFILE_OPENW = 90;
  public int JJTFILE_OPENA = 91;
  public int JJTFILE_CLOSE = 92;
  public int JJTFILE_GETSTR = 93;
  public int JJTFILE_GETLINE = 94;
  public int JJTFILE_PUTSTR = 95;
  public int JJTFILE_PUTLINE = 96;
  public int JJTFILE_FLUSH = 97;
  public int JJTFILE_ISFILE = 98;
  public int JJTFILE_RENAME = 99;
  public int JJTFILE_REMOVE = 100;
  public int JJTSLEEP = 101;
  public int JJTIDENT = 102;
  public int JJTARRAYNUM = 103;
  public int JJTFUNCTIONCALL = 104;
  public int JJTRETURN = 105;
  public int JJTBREAK = 106;
  public int JJTLITERAL = 107;
  public int JJTFLOATLITERAL = 108;
  public int JJTTRUE = 109;
  public int JJTFALSE = 110;
  public int JJTSTRLIT = 111;
  public int JJTEXTRA_STR = 112;


  public String[] jjtNodeName = {
    "IntVUnit",
    "ErrorOccur",
    "Function",
    "Block",
    "FunctionVar",
    "VarDecl",
    "Decl",
    "Array",
    "void",
    "AssignStats",
    "AssignStat",
    "IfStat",
    "RepeatUntil",
    "ForStatAdd",
    "WhileSwitchFor",
    "Case",
    "Label",
    "GetStat",
    "PutStat",
    "ORNode",
    "ANDNode",
    "NOTNode",
    "EQNode",
    "NTNode",
    "LSNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "SurNode",
    "MinNode",
    "Get",
    "Random",
    "Sine",
    "Cosine",
    "Tangent",
    "Sqrt",
    "Floor",
    "Ceil",
    "Round",
    "Abs",
    "Log",
    "Int",
    "Long",
    "Length",
    "Append",
    "Substring",
    "Insert",
    "Replace",
    "Extract",
    "Str2Int",
    "Int2Str",
    "Compare",
    "gOpenWindow",
    "gOpenGraphWindow",
    "gCloseWindow",
    "gClearWindow",
    "gSaveWindow",
    "gSetOrigin",
    "gSetMap",
    "gSetFillColor",
    "gSetLineColor",
    "gSetTextColor",
    "gSetFont",
    "gSetFontType",
    "gSetFontSize",
    "gSetDotShape",
    "gSetArrowDir",
    "gSetArrowType",
    "gSetLineShape",
    "gSetLineWidth",
    "gDrawPoint",
    "gDrawLine",
    "gDrawText",
    "gDrawCircle",
    "gFillCircle",
    "gDrawOval",
    "gFillOval",
    "gDrawBox",
    "gFillBox",
    "gDrawArc",
    "gFillArc",
    "gDrawPolygon",
    "gFillPolygon",
    "gDrawPolyline",
    "gDrawImage",
    "File_openr",
    "File_openw",
    "File_opena",
    "File_close",
    "File_getstr",
    "File_getline",
    "File_putstr",
    "File_putline",
    "File_flush",
    "File_isfile",
    "File_rename",
    "File_remove",
    "Sleep",
    "Ident",
    "ArrayNum",
    "FunctionCall",
    "Return",
    "Break",
    "Literal",
    "FloatLiteral",
    "True",
    "False",
    "Strlit",
    "EXTRA_STR",
  };
}
/* JavaCC - OriginalChecksum=9a9b151bbd2eaea28940902cf09e7fc1 (do not edit this line) */
